### ISSUE TITLE
ajax совместимость с другими модулями

### ISSUE THREAD

**Issue by gastranom** [San-Dev/DLE-Favorites#1]
У меня установлена например AJAX модуль сортировка новостей, и когда я меняю сортировку закладки перестают работать, как правильно их объединять? Может какой-то файл нужно подключить в другой модуль чтобы так сказать интегрировать его в ajax sort ? Заранее спасибо!

**Comment by San-Dev** [comment]
Вам нужно обратиться к автору того модуля, чтобы он в нужном месте подключил этот модуль.
Подключатся он таким образом:
```
require_once ENGINE_DIR . '/mods/favorites/class.favorites.php';
(new Sandev\Favorites)->setContent($tpl->result['main']);
```
где **$tpl->result['main']** - переменная с содержимым шаблона.
